# This file contains values from Cookiecutter

default_context:
  project_name: "filigree"
  project_description: "`filigree` is a Python cli/package"
  organization: "Daisie-Lab"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "daisie-lab"
  email: "eric.lacosse@research.fchampalimaud.org"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "cli"
